### ISSUE TITLE
کرش کردن گهگاه بازی در هنگام اینیت شدن  پرداخت کافه بازار

### ISSUE THREAD

**Issue by hamedrajabi** [cafebazaar/CafebazaarUnity#32]
سلام 

Error AndroidRuntime java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bazaar.util.IAB.isBillingSupported(int, java.lang.String, com.bazaar.util.communication.BillingSupportCommunication)' on a null object reference

at com.bazaar.util.IabHelper.checkBillingSupported(IabHelper.java:209)
at com.bazaar.util.IabHelper.access$000(IabHelper.java:63)
at com.bazaar.util.IabHelper$1.connected(IabHelper.java:184)
at com.bazaar.util.ServiceIAB$1.onServiceConnected(ServiceIAB.java:70)

سلام
من گهگاهی با این خطا در یکی از بازی ها مواجه میشم

این خط خطا میدهد.
NullPointerException
checkBillingSupported(IabHelper.java:209)
دلیلش چه چیزی هستش؟؟

دلیلش رو متوجه نمیشم با اینکه از خود کتابخونه کافه بازار استفاده میکنم و هنگام خروج 

   هم انجام میدم unbindService()
   
   بنظر بیشتر در اندروید 7 و 8 پیش اومده

**Comment by AliAriyamanesh** [comment]
من از یونیتی استفاده میکنم و همین مشکل رو دارم .
روی گوشی آنر 8 بازی رو اجرا میکنم که اندرویدش 7 هست 
چند وقت پیش اصلا پرداخت درون برنامه ای بازار برام باز نمیشد که کافه بازار رو حذف و دوباره نصب کردم حل شد ولی حالا به این مشکل خوردم

**Comment by hamedrajabi** [comment]
بنظر مشکل رو حل کردم

قبلا تو منو اصلی کافه بازار رو اینیت میکردم

الان آوردمش تو اسپلش اسکرین و اینیت کافه بازار رو فراخوانی میکنم

دیگه مشکلی پیش نیومده

 
البته  این قطعه کد هم حتما باید هنگام خروج از بازی 
نوشته شده باشه

 private void OnApplicationQuit()
    {
        BazaarIAB.unbindService();
    }

**Comment by AminSojoudi** [comment]
من باگ رو برطرف کردم متاسفانه دوستان کافه بازار کلا این ریپو رو به حال خودش ول کردن
از اینجا می تونید نسخه جدید رو بگیرید
روی بازی دبرناشو تست کردیم مشکل برطرف شده
https://github.com/AminSojoudi/CafebazaarUnity.git
