### ISSUE TITLE
خطا در دریافت خرید های قبلی کاربر

### ISSUE THREAD

**Issue by AminSojoudi** [cafebazaar/CafebazaarUnity#37]
خطا در دریافت خرید های قبلی کاربر:
```
# Type of exception: java.lang.NullPointerException
# Exception message: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
# Thread name: Thread-75
# Stacktrace: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
	at com.bazaar.util.ServiceIAB.getPurchases(ServiceIAB.java:265)
	at com.bazaar.util.IabHelper.queryPurchases(IabHelper.java:753)
	at com.bazaar.util.IabHelper$5.run(IabHelper.java:585)
	at java.lang.Thread.run(Thread.java:784)
```

**Comment by Enzx** [comment]
ببخشید من اینجا رو دیر دیدم اما این بسته دیگه پشتیبانی نمی‌شه. نسخه‌ی کامل که پشتیبانی می‌شه اینه:
https://github.com/cafebazaar/unitypurchasing

**Comment by AminSojoudi** [comment]
باشه، ممنونم،
